version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: sudo mkdir node_modules/
      - run: sudo chmod 777 node_modules
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
