version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run: npm run lint
  test:
    steps:
      - checkout
      - run: npm run test
  analyze:
    steps:
      - checkout
      - run: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
